services:
  - type: web
    name: tg-telegram-userbot
    runtime: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: TG_API_ID
        sync: false
      - key: TG_API_HASH
        sync: false
      - key: SESSION_STRING
        sync: false
      - key: SOURCE_CHAT_ID
        value: "-1004498861542"
      - key: WEB_ADMIN_API
        sync: false
      - key: WEB_ADMIN_API_TOKEN
        sync: false
      - key: API_SECRET
        sync: false
      - key: PORT
        value: "10000"
